language: ruby

rvm:
  - 1.9.3

bundler_args: --without development

branches:
  only:
    - master
    - develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  email:
    - kbennoune@gmail.com
    - ddavis1@gmail.com
