defaults: &defaults
  host: localhost
  preload_models: false

development:
  <<: *defaults
  database: rubeque_dev

test:
  <<: *defaults
  database: rubeque_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
